"""Rebuild the frozen benchmark case bytes from their seed fields."""
import argparse
import json
import pathlib
import sys

import chess

from controller_operations.engine import rank_moves


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
CASES_PATH = (
    REPO_ROOT / "backend" / "tests" / "fixtures"
    / "machine_readable_move_prompt" / "cases.json"
)


def _rebuild_case(seed):
    previous_fen = seed["prev_fen"]
    last_move = seed["last_move"]
    if last_move is None:
        fen = seed["fen"]
        rebuilt_last = None
    else:
        board = chess.Board(previous_fen)
        move = chess.Move.from_uci(last_move["uci"])
        if move not in board.legal_moves:
            raise ValueError(f"{seed['id']}: last move is not legal")
        rebuilt_last = {"uci": move.uci(), "san": board.san(move)}
        board.push(move)
        fen = board.fen()

    board = chess.Board(fen)
    return {
        "id": seed["id"],
        "phase": seed["phase"],
        "tone_tag": seed["tone_tag"],
        "message": seed["message"],
        "prior_tone": seed["prior_tone"],
        "prev_fen": previous_fen,
        "last_move": rebuilt_last,
        "fen": fen,
        "candidates": [list(pair) for pair in rank_moves(board)],
    }


def generated_bytes():
    frozen = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    payload = {
        "version": frozen["version"],
        "cases": [_rebuild_case(case) for case in frozen["cases"]],
    }
    return (json.dumps(payload, indent=2, ensure_ascii=False) + "\n").encode()


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", required=True)
    parser.parse_args(argv)
    expected = CASES_PATH.read_bytes()
    actual = generated_bytes()
    if actual != expected:
        print("cases.json does not match regenerated bytes", file=sys.stderr)
        return 1
    print("cases.json matches regenerated bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
